name: Build

on:
  push:
    paths:
    - .github/workflows/build.yml
    - Libraries/**
    - Source/**
    - Unity/**

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Set up Beat Saber
      uses: nicoco007/setup-beat-saber@main
      with:
        access-token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
        additional-dependencies: '{ "XR Hands": "^1.1.0", "OpenVR API": "^2.0.0" }'
        aliases: '{ "DynamicBone": "Dynamic Bone", "FinalIK": "Final IK" }'
        manifest: ${{ github.workspace }}\Source\CustomAvatar\manifest.json

    - name: Add NuGet source
      run: dotnet nuget update source "nicoco007 GitHub Packages" --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

    - name: Build Release
      id: build-release
      run: dotnet build Source\CustomAvatar\CustomAvatar.csproj -c Release

    - name: Upload Release
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build-release.outputs.artifact-name }}
        path: ${{ steps.build-release.outputs.artifact-path }}

    - name: Build Editor
      id: build-editor
      run: dotnet build Source\CustomAvatar-Editor\CustomAvatar-Editor.csproj -c Release

    - name: Upload Editor
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build-editor.outputs.artifact-name }}
        path: ${{ steps.build-editor.outputs.artifact-path }}
    
    - name: Upload Unity Project
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build-editor.outputs.unity-project-name }}
        path: Unity\BeatSaberCustomAvatars
